intranet/fairintranet/technicians/urls.py
from __future__ import unicode_literals
from __future__ import absolute_import

from django.conf.urls import url


from . import views
from django.shortcuts import redirect

app_name = 'technicians'


urlpatterns = [
    url(r'^register-computer/(?P<label>.+)/$', views.register_computer_installation, name='register_computer_installation'),
    url(r'^computer/login/(?P<label>[\w\d]+)/(?P<user>\w+)/$', views.computer_login, name='computer_login'),
    url(r'^computer/logout/(?P<label>[\w\d]+)/(?P<user>\w+)/$', views.computer_logout, name='computer_logout'),
    url(r'^computer/$', views.ComputerList.as_view(), name='computer_list'),
    url(r'^computer/(?P<pk>\d+)/log/$', views.ComputerLog.as_view(), name='computer_log'),
    url(r'^computer/(?P<pk>\d+)/log/create/$', views.ComputerLogAdd.as_view(), name='computer_log_add'),
    url(r'^$', lambda x: redirect('technicians:computer_list'),)
]

intranet/fairintranet/technicians/models.py
from __future__ import unicode_literals
from __future__ import absolute_import

from django.core.validators import RegexValidator
from django.db import models
from django.utils.translation import ugettext_lazy as _

from . import settings


class Inventory(models.Model):
    
    label = models.CharField(
        max_length=64,
        verbose_name=_("label of computer"),
        help_text=settings.LABEL_VALIDATION_HELP,
        validators=[RegexValidator(
            regex=settings.LABEL_VALIDATION,
            message=settings.LABEL_VALIDATION_HELP,
        )]
    )
    created = models.DateTimeField(
        verbose_name=_("created"),
        blank=True,
        null=True,
        auto_now_add=True,
    )
    modified = models.DateTimeField(
        verbose_name=_("modified"),
        blank=True,
        null=True,
        auto_now=True,
    )
    former_inventory = models.BooleanField(
        verbose_name=_("former inventory"),
        help_text=_("Means that the item is no longer at the facility"),
        default=False,
    )
    
    class Meta:
        ordering = ("label",)

    def __str__(self):
        return self.label.upper()


class Computer(Inventory):
    
    last_installed = models.DateTimeField(
        verbose_name=_("last installed"),
        blank=True,
        null=True,
    )

    def __str__(self):
        if not self.former_inventory:
            return "Computer {}".format(self.label.upper())
        return "Computer {} (removed)".format(self.label.upper())


class Screen(Inventory):
    
    def __str__(self):
        return "Screen {}".format(self.label.upper())


class Printer(Inventory):
    
    def __str__(self):
        return "Printer {}".format(self.label.upper())


class ComputerSession(models.Model):
    
    computer = models.ForeignKey('Computer', on_delete=models.CASCADE)
    started = models.DateTimeField(auto_now_add=True)
    ended = models.DateTimeField(null=True, blank=True)
    username = models.CharField(blank=True, null=True, max_length=32)
    
    class Meta:
        verbose_name = _("Computer session")
        get_latest_by = "started"


class LogMessage(models.Model):
    
    inventory = models.ForeignKey(
        'Inventory',
        verbose_name=_("last installed"),
        blank=True,
        null=True,
        on_delete=models.CASCADE,
    )
    message = models.TextField(
        verbose_name=_("message"),
    )
    technician = models.CharField(
        verbose_name=_("technician name"),
        blank=True,
        null=True,
        max_length=128,
    )
    created = models.DateTimeField(
        verbose_name=_("created"),
        blank=True,
        null=True,
        auto_now_add=True,
    )
    modified = models.DateTimeField(
        verbose_name=_("modified"),
        blank=True,
        null=True,
        auto_now=True,
    )
    resolved = models.BooleanField(
        verbose_name=_("has been resolved"),
        default=False,
    )
    removed = models.BooleanField(
        verbose_name=_("removed this inventory"),
        default=False,
    )
    
    class Meta:
        verbose_name = _("Log message")
        get_latest_by = "created"
    
    def save(self, force_insert=False, force_update=False, using=None, 
        update_fields=None):
        if self.removed:
            self.inventory.former_inventory = True
            self.inventory.save()
        return models.Model.save(self, force_insert=force_insert, force_update=force_update, using=using, update_fields=update_fields)
    

intranet/fairintranet/technicians/forms.py
from __future__ import unicode_literals
from __future__ import absolute_import

from django import forms

from . import models


class LogMessageForm(forms.ModelForm):
    
    inventory = forms.ModelChoiceField(models.Inventory.objects.all(), widget=forms.HiddenInput())
    
    class Meta:
        model = models.LogMessage
        exclude = ()

intranet/fairintranet/technicians/views.py
from __future__ import unicode_literals
from __future__ import absolute_import

from django.http import HttpResponse
from django.shortcuts import get_object_or_404, redirect
from django.utils import timezone

from . import forms
from . import models
from django.views.generic.list import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import CreateView


class ComputerList(ListView):
    
    template_name = "technicians/computer_list.html"
    model = models.Computer
    context_object_name = "computers"


class ComputerLog(DetailView):
    
    template_name = "technicians/computer_log.html"
    model = models.Computer
    context_object_name = "computer"
    
    def get_context_data(self, **kwargs):
        c = DetailView.get_context_data(self, **kwargs)
        c['log_messages'] = models.LogMessage.objects.filter(inventory=c['computer'])
        c['log_form'] = forms.LogMessageForm(initial={'inventory': c['computer']})
        return c


class ComputerLogAdd(CreateView):
    
    model = models.LogMessage
    form_class = forms.LogMessageForm
    template_name = "technicians/log_message_add.html"
    
    def dispatch(self, request, *args, **kwargs):
        self.computer = get_object_or_404(models.Computer, pk=kwargs.pop('pk'))
        return CreateView.dispatch(self, request, *args, **kwargs)
    
    def form_valid(self, form):
        log = form.save()
        return redirect("technicians:computer_log", pk=log.inventory.pk)
    
    def get_context_data(self, **kwargs):
        c = CreateView.get_context_data(self, **kwargs)
        c['computer'] = self.computer
        return c
    
    def get_initial(self):
        return {'inventory': self.computer}


def register_computer_installation(request, label=None):

    computer, __ = models.Computer.objects.get_or_create(label=label)
    computer.last_installed = timezone.now()
    computer.save()

    return HttpResponse("OK")


def computer_login(request, label="", user=""):
    
    computer = get_object_or_404(models.Computer, label__iexact=label)
    
    models.ComputerSession.objects.create(
        computer=computer,
        username=user
    )

    return HttpResponse("OK")


def computer_logout(request, label="", user=""):
    
    computer = get_object_or_404(models.Computer, label__iexact=label)
    
    models.ComputerSession.objects.filter(
        computer=computer,
        username=user,
        ended=None,
    ).update(ended=timezone.now())

    return HttpResponse("OK")

intranet/fairintranet/technicians/templates/technicians/base.html
{% extends "base.html" %}

{% block content %}

  {% block technicians_content %}
  {% endblock %}
  
{% endblock %}

intranet/fairintranet/technicians/templates/technicians/computer_list.html
{% extends "technicians/base.html" %}

{% block technicians_content %}

  <h1 class="page-header">Computers</h1>
  
  
  <table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Computer</th>
      <th>Last installed</th>
      <th>User logged in</th>
      <th>Latest log</th>
      <th></th>
    </tr>
  </thead>
  {% for computer in computers %}
  
    <tr>
      <td>{{ computer.label|upper }}</td>
      <td>{{ computer.last_installed|default:"Not installed yet" }}</td>
      <td>{{ computer.computersession_set.all.latest.username|default:"No one registered" }}</td>
      <td>
        {% with computer.logmessage_set.all.latest as log %}
          {{ log.technician|default:"No name" }}, {{ log.created }}
        {% endwith%}
      </td>
      <td style="width: 1px; white-space: nowrap; text-align: right">
        <a href="{% url 'technicians:computer_log' pk=computer.pk %}" class="btn btn-default">Go to log</a>
      </td>
    </tr>
  
  {% empty %}
    <tr>
      <td colspan="100">No computers found</td>
    </tr>
  {% endfor %}
  </table>

{% endblock %}

intranet/fairintranet/technicians/templates/technicians/computer_log.html
{% extends "technicians/base.html" %}

{% block technicians_content %}

  <h1 class="page-header">Log for: {{ computer }}</h1>
  
  <table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Message</th>
      <th>By</th>
      <th>When</th>
      <th>Changed</th>
      <th>Resolved</th>
      <th></th>
    </tr>
  </thead>
  {% for log in log_messages %}
  
    <tr>
      <td>{{ log.message }}</td>
      <td>{{ log.technician|default:"Anonymous" }}</td>
      <td>{{ log.created }}</td>
      <td>{{ log.modified }}</td>
      <td>{{ log.resolved|yesno }}</td>
      <td style="width: 1px; white-space: nowrap; text-align: right">
        <a href="" class="btn btn-default">Mark resolved</a>
      </td>
    </tr>
  
  {% empty %}
    <tr>
      <td colspan="100">No log messages found</td>
    </tr>
  {% endfor %}
  </table>
  
  <h2>Add log message</h2>  
  
  <form method="POST" action="{% url 'technicians:computer_log_add' computer.pk %}">
  {% csrf_token %}
  <table class="table table-striped table-bordered">
  
    {{ log_form.as_table }}
  
  </table>
  
  <p>
    <button type="submit">Save</button>
  </p>
  
  </form>


{% endblock %}

intranet/fairintranet/technicians/templates/technicians/log_message_add.html
{% extends "technicians/base.html" %}

{% block technicians_content %}

  <h1 class="page-header">Add Log Message</h1>
  
  <form method="POST">
  {% csrf_token %}
  <table class="table table-striped table-bordered">
  
    {{ form.as_table }}
  
  </table>
  
  <p>
    <button type="submit">Save</button>
  </p>
  
  </form>

{% endblock %}